name:                foam-eng
version:             0.1.0.0
github:              "githubuser/foam-eng"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/foam-eng#readme>

# @NOTE: is there anyway to make this automated?
# like a `stack install` or something? I manually put these in.

dependencies:
- aeson >= 1.4.2.0
- attoparsec >= 0.13.2.2
- base >= 4.7 && < 5
- base-compat >= 0.10.5
- bytestring >= 0.10.8.2
- directory >= 1.3.3.0
- http-media >= 0.7.1.3
- lucid >= 2.9.11
- mtl >= 2.2.2
- time >= 1.8.0.2
- servant >= 0.15
- servant-server >= 0.15
- string-conversions >= 0.4.0.1
- wai >= 3.2.2.1
- warp >= 3.2.28
- blaze-markup >= 0.8.2.2
- blaze-html >= 0.9.1.1

library:
  source-dirs: src

executables:
  foam-eng-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - foam-eng

tests:
  foam-eng-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - foam-eng
